---
title: "Launch Event: Lightning Talks"
author: "R-Ladies Sydney"
date: 2018-06-13
tags:
- meetup
slug: lightning-talks
editor_options: 
  chunk_output_type: console
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We are super excited to announce that [R-Ladies Sydney will launch on June 20th 2018](https://www.meetup.com/en-AU/rladies-sydney/events/251094494/) `r emo::ji("tada")`. For our first event, we want everyone to meet someone new and learn something new so we plan to host a series of lightning talks `r emo::ji("lightning")`. You are all invited to come along! We have an awesome lineup of speakers, listed below, so come along and join in!

<br>

## Jessica Lee 

- *Title*: [**Why I R?**](/post/2018-06-13-lightning-talks_files/JessicaLee.pdf)
- *Contact*: <a href="mailto:jesssica.lee88@gmail.com"><i class="fa fa-envelope"></i></a>
- *Bio*: I am a postdoctoral fellow working at the School of Psychology at the University of New South Wales. I am investigating how we generalize simple learned associations (e.g., tone-shock) and the role of inductive reasoning processes in such generalization. My background is in associative learning. I use R for data preprocessing, graphing, analysis, and computational modeling. 

<br>

## Emi Tanaka

- *Title*: [**Making a Shiny interactive web application using R**](https://emitanaka.github.io/talk/rladies-shiny/)
- *Contact*: <a href="https://twitter.com/statsgen"><i class="fa fa-twitter"></i></a>
- *Bio*: Emi is a lecturer in statistics at the School of Mathematics and Statistics, the University of Sydney. She uses R all the time for her research to develop useful statistical applied tools with a particular focus on agriculture. She enjoys working in a collaborative environment with people from diverse backgrounds, with an aim to enhance knowledge and understanding of the real world data.

<br>

## Wendy Wong

- *Title*: [**Transitioning from financial planning to data science - Using R in insurance and agile data science projects in government**](/post/2018-06-13-lightning-talks_files/WendyWong.pdf)
- *Contact*: <a href="mailto:wendy-wong@hotmail.com"><i class="fa fa-envelope"></i></a>
<a href="https://twitter.com/abc_wendsss"><i class="fa fa-twitter"></i></a>
<a href="https://www.linkedin.com/in/wendywong7/"><i class="fa fa-linkedin"></i></a>
- *Bio*: Wendy Wong is a finance and analytics professional with 12 year's experience in financial planning and funds management. She is a Master of Data Science and Innovation student at the University of Technology and is a data science intern working as a Data Analyst at the Australian Taxation Office and a Reporting Analyst at Allianz Australia. She uses R for predictive modelling in agile sprint projects in Government for debt research using logistic regression, decision tree and random forest algorithms to analyse client behaviours with blended third party data. Wendy is a data science mentor and recently coached a team in NSW bushfire data and uses Tableau, Microstrategy and PowerBI to visualise data. I have used Rstudio via dropbox at Unearthed hackathon in 2016.

<br>

## Sarah Romanes 

- *Title*: [**My long journey learning R - then and now**](https://sarahromanes.github.io/talk/r-ladies-talk/)
- *Contact*: <a href="sarahromanes.github.io"><i class="fa fa-address-card"></i></a>
<a href="mailto:sarah.romanes@sydney.edu.au"><i class="fa fa-envelope"></i></a>
<a href="https://twitter.com/sarah_romanes"><i class="fa fa-twitter"></i></a>
<a href="https://www.linkedin.com/in/sarah-romanes-939a325b/"><i class="fa fa-linkedin"></i></a>
- *Bio*: Sarah is a PhD student in Statistics and Postgraduate Teaching Fellow at the University of Sydney. Originally from a mathematical statistics background,  R is core to her research in developing statistical machine learning techniques, in which she focuses on developing fast and interpretable algorithms for high dimensional data. Recently she has developed R packages based on her research, and enjoys exploring the ever growing capabilities of R. Sarah also enjoys lecturing and tutoring first year students in statistics, and showing them that statistics isn’t all that bad when you have R! 

<br>

## Zoe Meers

- *Title*: [**ggparliament: Parliament plots in the tidyverse**](https://zmeers.github.io/R-LadiesSydney/slides/slides.html)
- *Contact*: <a href="mailto:zoe.meers@sydney.edu.au"><i class="fa fa-envelope"></i></a>
<a href="https://twitter.com/zoe_meers"><i class="fa fa-twitter"></i></a>
- *Bio*: Zoe is a data visualization analyst and research assistant in political science at the US Studies Centre at the University of Sydney. She uses R in her data visualization work and in quantitative social science research. She is a big fan of Hadley Wickham’s Tidyverse. Previously, she was a data journalism fellow at the ABC and the Google News Lab. Prior to that, she studied politics and statistics at university in the US, where she developed a strong interest in using data to explain political phenomena. Currently, she is working on several R packages.

<br>

## Lovisa Lannesand

- *Title*: [**From Excel to R in the world of finance**](/post/2018-06-13-lightning-talks_files/LovisaLannesand.html)
- *Contact*: <a href="mailto:Lovisa.Lannesand@macquarie.com"><i class="fa fa-envelope"></i></a>
- *Bio*: I am born and raised in Sweden, but at age 18 I was sick of long and cold winters and decided to move to Sydney for 6 months. Seven years has passed and I am still here, however no longer sharing a house with 7 people, and I still love the city!
I completed my Bachelor of Business at UTS in Sydney in 2013, and it was during this period I gained an interest in statistics and data science.  I now work as a quantitative analyst for Macquarie bank, in the Corporate Asset Finance group. When I first started the role R was completely new to me, but when I realized how efficient and effective the language was I invested the time to learn. Today I use R on a daily basis for a wide range of processes, such as data cleaning / analysis, financial modelling and reporting.

<br> 
 
## Kate Dodds

- *Title*: [**Learning the lingo - An R newbie’s perspective**](/post/2018-06-13-lightning-talks_files/KateDodds.pdf)
- *Contact*: <a href="mailto:kate.dodds@hdr.mq.edu.au"><i class="fa fa-envelope"></i></a>
<a href="https://twitter.com/kate_c_dodds"><i class="fa fa-twitter"></i></a>
<a href="https://www.linkedin.com/in/kate-dodds-/"><i class="fa fa-linkedin"></i></a>
- *Bio*: Kate is a PhD student at Macquarie University, investigating eco-engineering techniques for artificial structures in the marine environment. She comes from an environmental consulting background and has previously dabbled in Matlab and Python. R is the language of choice in her department at Uni and she’s excited by the tip of the iceberg that she’s discovered so far. She’s really interested in uncovering the rest and working out how best to do this.

<br>

## Charles Gray

- *Title*: [**My experience at runconf18**](/post/2018-06-13-lightning-talks_files/CharlesGray/lightning-talk.html)
- *Contact*: <a href="https://twitter.com/cantabile"><i class="fa fa-twitter"></i></a>
- *Bio*: Charles T. Gray is a tidyverse enthusiast, PhD (meta-analysis) student at La Trobe, and reformed musician. She is a member of R-Ladies Remote and is known for her math advocacy work as a [Mathbassador for Choose Maths](http://choosemaths.org.au/charles-gray/).

<br><br><br>
